# Generated by Django 4.1.6 on 2023-02-09 09:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_work'),
    ]

    operations = [
        migrations.DeleteModel(
            name='work',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='todo',
            name='task_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
