# Generated by Django 4.1.6 on 2023-02-09 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_delete_work_remove_todo_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ('-task_created',)},
        ),
    ]
